name: hovernet
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - python=3.6.12
  - pip=20.3.1
  - openslide
  - pip:
    - -r file:requirements.txt
    - openslide-python==1.1.2
